import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getCssText } from "@jimmydalecleveland/stitches-ui-example";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <head>
        <style
          dangerouslySetInnerHTML={{ __html: getCssText() }}
          id="stitches"
        />
        <title>Default Title</title>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
